name: Build EXE

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: List files at repo root (debug)
        run: dir

      - name: List files inside project folder (debug)
        run: |
          cd SmartCampusDashboardFull
          dir

      - name: Setup MSBuild
        uses: microsoft/setup-msbuild@v2

      - name: Build solution
        run: msbuild SmartCampusDashboardFull/SmartCampusDashboard.sln /p:Configuration=Release /restore

      - name: Upload build output
        uses: actions/upload-artifact@v4
        with:
          name: SmartCampusDashboard-output
          path: |
            SmartCampusDashboardFull/**/bin/Release/*.exe
            SmartCampusDashboardFull/**/bin/Release/*.dll
